# Generated by Django 5.2.8 on 2025-11-12 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150, unique=True)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('email_empresa', models.EmailField(max_length=100)),
                ('pais_origen', models.CharField(max_length=50)),
                ('contacto_principal', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('marca', models.CharField(max_length=100)),
                ('img_url', models.URLField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='app_victorysports.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True)),
                ('cantidad_comprada', models.IntegerField(default=1)),
                ('referencia_pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('es_proveedor_activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_proveedor', to='app_victorysports.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_producto', to='app_victorysports.proveedor')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedores',
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
