# Generated by Django 5.2.8 on 2025-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_victorysports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
            },
        ),
    ]
